[project]
name = "staff-crm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.6",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "django-rest-framework>=0.1.0",
    "django-scalar>=0.2.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "psycopg2>=2.9.12",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]

[tool.ruff]
line-length = 88
fix = true

[tool.ruff.format]
line-ending = "auto"

[tool.ruff.lint]
fixable = ["F401"]
