# Generated by Django 6.0.6 on 2026-07-15 14:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='not_future_birth_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2026, 7, 15))), name='not_future_birth_date'),
        ),
    ]
