# Generated by Django 6.0.6 on 2026-08-08 09:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_at_department_description_and_more'),
        ('employees', '0006_alter_employee_employment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='not_future_birth_date',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2026, 8, 8))), name='not_future_birth_date'),
        ),
    ]
