# Generated by Django 6.0.6 on 2026-08-09 08:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_at_department_description_and_more'),
        ('employees', '0008_employee_termination_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='not_future_birth_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2026, 8, 9))), name='not_future_birth_date'),
        ),
    ]
