# Generated by Django 6.0.6 on 2026-08-10 09:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_at_department_description_and_more'),
        ('employees', '0009_remove_employee_not_future_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('terminate_employee', 'Can terminate employee'), ('view_terminated_employee', 'Can view terminated employee')]},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='not_future_birth_date',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2026, 8, 10))), name='not_future_birth_date'),
        ),
    ]
