# Generated by Django 6.0.6 on 2026-08-23 09:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_at_department_description_and_more'),
        ('employees', '0011_remove_employee_not_future_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_imports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ADDED', 'Added'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('row_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('terminate_employee', 'Can terminate employee'), ('view_terminated_employee', 'Can view terminated employee'), ('import_employee', 'Can import employee')]},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='not_future_birth_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2026, 8, 23))), name='not_future_birth_date'),
        ),
        migrations.AddField(
            model_name='employeeimportjob',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importjobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.employeeimportjob'),
        ),
        migrations.AddConstraint(
            model_name='importjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='unique_job_row_number'),
        ),
    ]
